### ISSUE TITLE
Is it possible to disable the node Integration option to use this boilerplate?

### ISSUE THREAD

**Issue by gasscoelho** [diego3g/electron-typescript-react#22]
I was doing some research about security in Electron and found we should not enable nodeJs integration for Remote Content. 

https://github.com/electron/electron/blob/master/docs/tutorial/security.md (second option)

So I tried to disable that option and got some issues -- I believe it was caused by some webpack configuration, not sure. 

![image](https://user-images.githubusercontent.com/33602013/92293530-ab378a80-eefa-11ea-9f93-6b602159b57b.png)

I'm not an expert in security but I like to follow as much as I can so I wonder if this should be a concern because basically we would be loading the Electron Renderer in localhost (dev environment) and in a static HTML page (prod environment), right?

What do you guys think?

**Comment by Wilgnne** [comment]
When trying to replicate I got the same error, it really seems to be something in the react webpack, more specifically in the devServer, since in a build everything seems to happen well

**Comment by Wilgnne** [comment]
I just found a solution to this problem, just change the webpack target of the react from `electron-renderer` to `web`, thus disabling all node integration.

`webpack/react.webpack.js`
```js
module.exports = {
  ...
  target: 'web',
  ...
}
```

**Comment by gasscoelho** [comment]
@Wilgnne Thank you so much for your solution, I really appreciate it!!
