### ISSUE TITLE
doubts - usability and roadmap

### ISSUE THREAD

**Issue by rodgomesc** [diego3g/electron-typescript-react#24]
what is  the motivation to create this project instead of use [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) that already has a very large and active community?

- is ready to use in production?
- the roadmap is public?

**Comment by rota-rossi** [comment]
I'm not into the development team here, but I guess the lack of typescript on the referred project, to name one.

**Comment by rodgomesc** [comment]
> I'm not into the development team here, but I guess the lack of typescript on the referred project, to name one.

@rota-rossi  the project i mentioned uses typescript too

**Comment by lociero** [comment]
@rodgomesc this one is simply more easy to use, good enough for people who just learns js/ts/react/electron and so on.
If u are experienced enough and work in a team, then ofc u should use the one u mentioned =)
