### ISSUE TITLE
Using @unform/web and @unform/core with the boilerplate is not working

### ISSUE THREAD

**Issue by paulohcasanova** [diego3g/electron-typescript-react#40]
Hi.
I've tried combining @unform/web and @unform/core to this boilerplate but the electron window displays a blank page when I add those dependencies.

Maybe there is a different configuration required in webpack for @unform to work ?

**Comment by diego3g** [comment]
Did you got any errors? I'm closing the issue as i did a full refactor of this boilerplate, so maybe you can try again and reopen the issue if the problem persists? Thanks!
